select * from recipe;
select * from categories;
select * from productionline;
select * from employee;
select * from branches;
select * from roles;
select * from bakedGoods;
select * from rawMaterials;
select * from nutritionFacts;